[tool.poetry]
name = "oop-home-work"
version = "0.1.0"
description = ""
authors = ["Aleksandr_Sotnikov <Sotnik617@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
